import { AlertCircle, BatteryMedium, CheckCircle2, Info, Wrench } from 'lucide-react';
import { Layout } from '../components/Layout';
import { StatusBadge } from '../components/StatusBadge';
import { demoAlerts } from '../lib/demo-data';

const groups = [
  { label: 'Critical', priority: 'CRITICAL' as const, icon: AlertCircle, tone: 'danger' as const },
  { label: 'Warning', priority: 'WARNING' as const, icon: BatteryMedium, tone: 'warning' as const },
  { label: 'Information', priority: 'INFO' as const, icon: Info, tone: 'neutral' as const },
];

export function AlertsPage() {
  return <Layout><div className="space-y-6"><section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-teal-700">Attention center</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Alerts</h1><p className="mt-1 text-slate-600">Safety, maintenance, battery, and system notifications for Demo Device.</p></div><StatusBadge tone="danger" label={`${demoAlerts.length} ACTIVE`} /></section><div className="grid gap-4 md:grid-cols-3">{groups.map(({ label, priority, icon: Icon, tone }) => <div key={label} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center gap-3"><Icon size={18} className={tone === 'danger' ? 'text-red-600' : tone === 'warning' ? 'text-amber-600' : 'text-slate-500'} /><span className="text-sm font-semibold text-slate-600">{label}</span></div><div className="mt-3 text-2xl font-bold text-slate-950">{demoAlerts.filter((alert) => alert.priority === priority).length}</div><div className="mt-1 text-xs text-slate-500">notification{demoAlerts.filter((alert) => alert.priority === priority).length === 1 ? '' : 's'}</div></div>)}</div><div className="space-y-4">{groups.map(({ label, priority, icon: Icon, tone }) => { const alerts = demoAlerts.filter((alert) => alert.priority === priority); return <section key={label}><div className="mb-3 flex items-center gap-2"><Icon size={18} className={tone === 'danger' ? 'text-red-600' : tone === 'warning' ? 'text-amber-600' : 'text-slate-500'} /><h2 className="text-lg font-bold">{label}</h2></div>{alerts.length === 0 ? <div className="rounded-xl border border-dashed border-slate-300 p-5 text-sm text-slate-500">No {label.toLowerCase()} alerts.</div> : <div className="space-y-3">{alerts.map((alert) => <article key={alert.id} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h3 className="font-bold text-slate-900">{alert.title}</h3><StatusBadge tone={tone} label={alert.priority} /></div><p className="mt-2 text-sm leading-6 text-slate-600">{alert.message}</p></div><span className="text-xs text-slate-400">{alert.time}</span></div><div className="mt-4 flex flex-wrap items-center gap-4 border-t border-slate-100 pt-3 text-xs font-medium text-slate-500"><span className="inline-flex items-center gap-1.5"><Wrench size={14} />Affected: {alert.affectedComponent}</span><span className="inline-flex items-center gap-1.5"><CheckCircle2 size={14} />Demo event {alert.id}</span></div></article>)}</div>}</section>; })}</div></div></Layout>;
}
