import { Activity, BatteryMedium, CheckCircle2, Gauge, Link2, Radio, SunMedium, Thermometer, Waves, Zap } from 'lucide-react';
import { Layout } from '../components/Layout';
import { StatusBadge } from '../components/StatusBadge';
import { demoDeviceStatus, demoInletReading, demoOutletReading, demoThresholds } from '../lib/demo-data';

type ReadingCardProps = { label: string; value: string; range: string; status: 'NORMAL' | 'WARNING' | 'CRITICAL'; icon: typeof Activity };

function ReadingCard({ label, value, range, status, icon: Icon }: ReadingCardProps) {
  const tone = status === 'CRITICAL' ? 'border-red-200 bg-red-50' : status === 'WARNING' ? 'border-amber-200 bg-amber-50' : 'border-slate-200 bg-white';
  return <div className={`rounded-xl border p-4 ${tone}`}><div className="flex items-center justify-between"><span className="text-sm font-semibold text-slate-700">{label}</span><Icon size={17} className="text-slate-500" /></div><div className="mt-3 flex items-end justify-between gap-2"><strong className="text-2xl text-slate-950">{value}</strong><StatusBadge tone={status === 'CRITICAL' ? 'danger' : status === 'WARNING' ? 'warning' : 'safe'} label={status} /></div><p className="mt-2 text-xs text-slate-500">Configured range: {range}</p></div>;
}

export function MonitoringPage() {
  return <Layout><div className="space-y-6"><section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-teal-700">Telemetry overview</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Water &amp; Sensor Monitoring</h1><p className="mt-1 text-slate-600">Live simulated readings from Demo Device</p></div><StatusBadge tone="warning" label="SIMULATED SENSOR DATA" /></section><div className="flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900"><Radio size={18} className="mt-0.5 shrink-0" /><span><strong>Simulation Mode</strong> — readings are generated demo data and are not from physical sensors.</span></div>
    <section><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-bold">Inlet water</h2><span className="text-xs font-semibold uppercase tracking-[0.12em] text-slate-500">Source check</span></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><ReadingCard label="pH" value={`${demoInletReading.ph}`} range={`${demoThresholds.inlet.ph.min}–${demoThresholds.inlet.ph.max}`} status="NORMAL" icon={Gauge} /><ReadingCard label="TDS" value={`${demoInletReading.tds} mg/L`} range={`≤ ${demoThresholds.inlet.tds.max} mg/L`} status="NORMAL" icon={Waves} /><ReadingCard label="Turbidity" value={`${demoInletReading.turbidity} NTU`} range={`≤ ${demoThresholds.inlet.turbidity.max} NTU`} status="NORMAL" icon={Activity} /><ReadingCard label="Temperature" value={`${demoInletReading.temperature}°C`} range={`${demoThresholds.inlet.temperature.min}–${demoThresholds.inlet.temperature.max}°C`} status="NORMAL" icon={Thermometer} /><ReadingCard label="Flow" value={`${demoInletReading.flowRate} L/h`} range={`${demoThresholds.inlet.flow.min}–${demoThresholds.inlet.flow.max} L/h`} status="NORMAL" icon={Zap} /></div></section>
    <section><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-bold">Outlet water</h2><span className="text-xs font-semibold uppercase tracking-[0.12em] text-red-600">Verification failed</span></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><ReadingCard label="pH" value={`${demoOutletReading.ph}`} range={`${demoThresholds.outlet.ph.min}–${demoThresholds.outlet.ph.max}`} status="NORMAL" icon={Gauge} /><ReadingCard label="TDS" value={`${demoOutletReading.tds} mg/L`} range={`≤ ${demoThresholds.outlet.tds.max} mg/L`} status="NORMAL" icon={Waves} /><ReadingCard label="Turbidity" value={`${demoOutletReading.turbidity} NTU`} range={`≤ ${demoThresholds.outlet.turbidity.max} NTU`} status="CRITICAL" icon={Activity} /><ReadingCard label="Temperature" value={`${demoOutletReading.temperature}°C`} range={`${demoThresholds.outlet.temperature.min}–${demoThresholds.outlet.temperature.max}°C`} status="NORMAL" icon={Thermometer} /><ReadingCard label="Flow" value={`${demoOutletReading.flowRate} L/h`} range={`${demoThresholds.outlet.flow.min}–${demoThresholds.outlet.flow.max} L/h`} status="NORMAL" icon={Zap} /></div></section>
    <section><h2 className="mb-3 text-lg font-bold">System status</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><ReadingCard label="UV module" value={`${demoDeviceStatus.health.uvHealth}% health`} range={`≥ ${demoThresholds.device.minUvHealth}%`} status="NORMAL" icon={SunMedium} /><ReadingCard label="Pump" value="IDLE" range="Must stop on rejection" status="NORMAL" icon={Zap} /><ReadingCard label="Simulated solenoid" value="LOCKED" range="Locked until verified" status="CRITICAL" icon={Link2} /><ReadingCard label="Battery" value={`${demoDeviceStatus.health.batteryLevel}%`} range={`≥ ${demoThresholds.device.minBattery}%`} status="WARNING" icon={BatteryMedium} /><ReadingCard label="Solar charging" value={`${demoDeviceStatus.health.solarVoltage} V`} range="Charging state" status="NORMAL" icon={SunMedium} /><ReadingCard label="Connectivity" value={demoDeviceStatus.networkStatus} range="Device link" status="NORMAL" icon={CheckCircle2} /></div></section>
  </div></Layout>;
}
